import { useState, forwardRef } from "react";
import { motion } from "framer-motion";
import { CardActionArea } from "@mui/material";

const CardPlant = forwardRef(({ plant }, ref) => {
  const { default_image, common_name, scientific_name } = plant;

  const [imageLoading, setImageLoading] = useState(true);
  const [pulsing, setPulsing] = useState(true);

  const imageLoaded = () => {
    setImageLoading(false);
    setTimeout(() => setPulsing(false), 600);
  };

  const plantBody = (
    <>
      <div
        className={`${pulsing ? "pulse" : ""
          } overflow-hidden max-auto shadow-lg rounded-md my-2`}
        style={{ width: "100%", background: "#ccc" }}
      >
        <CardActionArea>
          <motion.img
            src={default_image?.small_url}
            alt="image about the plant generated by api trefle"
            className="w-full"
            initial={{ height: "100px", opacity: 0 }}
            animate={{
              height: imageLoading ? "100px" : "auto",
              opacity: imageLoading ? 0 : 1,
            }}
            transition={
              ({ height: { delay: 0, duration: 0.4 } },
                { opacity: { delay: 0.5, duration: 0.4 } })
            }
            onLoad={imageLoaded}
          />
          <div className="flex flex-col gap-2 mt-4 bg-white w-4/5 mx-auto">
            <span className="tracking-[0.2rem] text-md font-bold uppercase">
              {common_name}
            </span>
            <span className="font-semibold">{scientific_name}</span>
          </div>
        </CardActionArea>
      </div>
    </>
  );

  const content = ref ? (
    <div ref={ref}>{plantBody}</div>
  ) : (
    <div>{plantBody}</div>
  );

  return content;
});

export default CardPlant;
